config/routes.rb
Smiles4usv3::Application.routes.draw do

  resources :contactos

  get "subscripciones/index"

  get "nosotros/index"

  get "contacto/index"

  resources :comentarios

  get "favoritos/index"

  get "password_resets/create"

  get "password_resets/edit"

  get "password_resets/update"

  get "usuarios/new"

  get "sessions/new"

  resources :usuarios

  get "sesion/iniciarsesion"

  get "sesion/post"

  get "sesion/registrarse"

  get "welcome/index"
  
  
  
  get "logout" => "sessions#destroy", :as => "logout"
get "login" => "sessions#new", :as => "login"
get "signup" => "usuarios#new", :as => "signup"
resources :usuarios
resources :sessions
  

  resources :posts
  resources :sesion
  
  resources :password_resets
 

 root :to => 'posts#inicio'

end

app/models/comentario.rb
class Comentario < ActiveRecord::Base
 
  attr_accessible :texto, :usuario_id
  
   validates_presence_of :texto
   validates :texto, :texto => { :maximun => 140 }
end

app/models/post.rb
class Post < ActiveRecord::Base
  attr_accessible :photo,:titulo, :usuario_id
 belongs_to :usuario
  FOTOS = File.join Rails.root, 'public','photo_store'
  after_save :guardar_foto
  def photo=(file_data)
    unless file_data.blank?
      @file_data = file_data
      self.extension = file_data.original_filename.split('.').last.downcase
    end
  end

  def photo_filename
    File.join FOTOS, "#{id}.#{extension}"
  end

  def photo_path
    "/photo_store/#{id}.#{extension}"
  end

  def has_photo?
    File.exists? photo_filename

  end

  private

  def guardar_foto
    if @file_data
      FileUtils.mkdir_p FOTOS
      File.open(photo_filename, 'wb') do |f|
        f.write(@file_data.read)
      end
      @file_data = nil
    end
  end
end

app/models/usuario.rb
class Usuario < ActiveRecord::Base
 has_many :posts
 authenticates_with_sorcery!
  attr_accessible :crypted_password, :email, :salt, :username, :password_confirmation , :password
  validates_confirmation_of :password, message: "Ambos campos deben coincidir", if: :password
  validates_presence_of :password, :on => :create
  validates_presence_of :email
  validates_uniqueness_of :email
end

app/controllers/comentarios_controller.rb
class ComentariosController < ApplicationController
  # GET /comentarios
  # GET /comentarios.json
  def index
    @comentarios = Comentario.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @comentarios }
    end
  end

  # GET /comentarios/1
  # GET /comentarios/1.json
  def show
    @comentario = Comentario.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @comentario }
    end
  end

  # GET /comentarios/new
  # GET /comentarios/new.json
  def new
    @comentario = Comentario.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @comentario }
    end
  end

  # GET /comentarios/1/edit
  def edit
    @comentario = Comentario.find(params[:id])
  end

  # POST /comentarios
  # POST /comentarios.json
  def create
    @comentario = Comentario.new(params[:comentario])

    respond_to do |format|
      if @comentario.save
        format.html { redirect_to @comentario, notice: 'Comentario was successfully created.' }
        format.json { render json: @comentario, status: :created, location: @comentario }
      else
        format.html { render action: "new" }
        format.json { render json: @comentario.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /comentarios/1
  # PUT /comentarios/1.json
  def update
    @comentario = Comentario.find(params[:id])

    respond_to do |format|
      if @comentario.update_attributes(params[:comentario])
        format.html { redirect_to @comentario, notice: 'Comentario was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @comentario.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comentarios/1
  # DELETE /comentarios/1.json
  def destroy
    @comentario = Comentario.find(params[:id])
    @comentario.destroy

    respond_to do |format|
      format.html { redirect_to comentarios_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/contacto_controller.rb
class ContactoController < ApplicationController
  def index
  end  
end

app/controllers/nosotros_controller.rb
class NosotrosController < ApplicationController
  def index
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  # GET /posts
  # GET /posts.json

  before_filter :require_login, :only => :secret
  def index
    @posts = Post.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @posts }
    end
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @post = Post.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @post }
    end
  end

  # GET /posts/new
  # GET /posts/new.json
  def new
    @post = Post.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @post }
    end
  end

  # GET /posts/1/edit
  def edit
    @post = Post.find(params[:id])
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(params[:post])

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Su post fue creado con exito!.' }
        format.json { render json: @post, status: :created, location: @post }
      else
        format.html { render action: "nuevo" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /posts/1
  # PUT /posts/1.json
  def update
    @post = Post.find(params[:id])

    respond_to do |format|
      if @post.update_attributes(params[:post])
        format.html { redirect_to @post, notice: 'Su post fue actualizado con exito!.' }
        format.json { head :no_content }
      else
        format.html { render action: "editar" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/sesion_controller.rb
class SesionController < ApplicationController
 before_filter :require_login, :only => :secret
  def iniciarsesion
  end

  def post
  end

  def registrarse
  end
  
  def destroy
  logout
  redirect_to root_url, :notice => "Logged out!"
end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
 before_filter :require_login, :only => :secret

def create
 usuario = login(params[:email], params[:password], params[:remember_me])
  if usuario
    redirect_back_or_to posts_path , :notice => "Logged in!"
  else
    flash.now.alert = "Email or password was invalid"
    render :new
  end
end

def destroy
  logout
  redirect_to root_url, :notice => "Logged out!"
end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/AsideIzquierdo_helper.rb
module AsideIzquierdoHelper
end

app/helpers/Aside_Izquierdo_helper.rb
module AsideIzquierdoHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comentarios_helper.rb
module ComentariosHelper
end

app/helpers/contacto_helper.rb
module ContactoHelper
end

app/helpers/contactos_helper.rb
module ContactosHelper
end

app/helpers/nosotros_helper.rb
module NosotrosHelper
end

app/helpers/password_resets_helper.rb
module PasswordResetsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sesion_helper.rb
module SesionHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/usuarios_helper.rb
module UsuariosHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/comentarios/_form.html.erb
<%# Conditionally set remote: true. Also, passing model name as data attribute %>
<% modal ||= false %>
<% remote = modal ? true : false %>

<%= form_for(@comentario) do |f| %>
  <% if @comentario.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comentario.errors.count, "error") %> prohibited this comentario from being saved:</h2>

      <ul>
      <% @comentario.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


	
  <div class="field">
    <h1>Comentarios</h1>
    	<br />
    <%= f.text_area :texto , :rows => 4, :cols => 50 %>
    
    <p>
    	 <div class="actions" >
			<button type="button" class="btn btn-default btn-sm">
				<span class="glyphicon glyphicon-heart-empty"></span> Me gusta
			</button>
			
			<button type="submit" class="btn btn-default btn-sm">

<span class="glyphicon glyphicon-comment"> </span> Comentar

</button>
</div>
    <!-- <%= f.submit "Comentar" , class: 'btn btn-default btn-sm' %> -->
 
  </div>
		</p>

 
<% end %>

app/views/comentarios/edit.html.erb
<h1>Editing comentario</h1>

<%= render 'form' %>

<%= link_to 'Show', @comentario %> |
<%= link_to 'Back', comentarios_path %>

app/views/comentarios/index.html.erb
<h1>Listing comentarios</h1>

<table>
  <tr>
    <th>Texto</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
  
  <%# Added Bootstrap data modal attribute %>


<% @comentarios.each do |comentario| %>
  <tr>
    <td><%= comentario.texto %></td>
    <td><%= link_to 'Show', comentario %></td>
    <td><%= link_to 'Edit', edit_comentario_path(comentario) %></td>
    <td><%= link_to 'Destroy', comentario, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>


<br />

<%= link_to 'New Comentario', new_comentario_path %>

app/views/comentarios/new.html.erb
<h1>New comentario</h1>

<%= render 'form' %>

<%= link_to 'Back', comentarios_path %>

app/views/comentarios/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Texto:</b>
  <%= @comentario.texto %>
</p>


<%= link_to 'Edit', edit_comentario_path(@comentario) %> |
<%= link_to 'Back', comentarios_path %>