config/routes.rb
Smiles4usv3::Application.routes.draw do

  resources :contactos

  get "subscripciones/index"

  get "nosotros/index"

  get "contacto/index"

  resources :comentarios

  get "favoritos/index"

  get "password_resets/create"

  get "password_resets/edit"

  get "password_resets/update"

  get "usuarios/new"

  get "sessions/new"

  resources :usuarios

  get "sesion/iniciarsesion"

  get "sesion/post"

  get "sesion/registrarse"

  get "welcome/index"
  
  
  
  get "logout" => "sessions#destroy", :as => "logout"
get "login" => "sessions#new", :as => "login"
get "signup" => "usuarios#new", :as => "signup"
resources :usuarios
resources :sessions
  

  resources :posts
  resources :sesion
  
  resources :password_resets
 

 root :to => 'posts#inicio'

end

app/models/comentario.rb
class Comentario < ActiveRecord::Base
 
  attr_accessible :texto, :usuario_id
  
   validates_presence_of :texto
   validates :texto, :texto => { :maximun => 140 }
end

app/models/post.rb
class Post < ActiveRecord::Base
  attr_accessible :photo,:titulo, :usuario_id
 belongs_to :usuario
  FOTOS = File.join Rails.root, 'public','photo_store'
  after_save :guardar_foto
  def photo=(file_data)
    unless file_data.blank?
      @file_data = file_data
      self.extension = file_data.original_filename.split('.').last.downcase
    end
  end

  def photo_filename
    File.join FOTOS, "#{id}.#{extension}"
  end

  def photo_path
    "/photo_store/#{id}.#{extension}"
  end

  def has_photo?
    File.exists? photo_filename

  end

  private

  def guardar_foto
    if @file_data
      FileUtils.mkdir_p FOTOS
      File.open(photo_filename, 'wb') do |f|
        f.write(@file_data.read)
      end
      @file_data = nil
    end
  end
end

app/models/usuario.rb
class Usuario < ActiveRecord::Base
 has_many :posts
 authenticates_with_sorcery!
  attr_accessible :crypted_password, :email, :salt, :username, :password_confirmation , :password
  validates_confirmation_of :password, message: "Ambos campos deben coincidir", if: :password
  validates_presence_of :password, :on => :create
  validates_presence_of :email
  validates_uniqueness_of :email
end

app/controllers/contacto_controller.rb
class ContactoController < ApplicationController
  def index
  end  
end

app/controllers/nosotros_controller.rb
class NosotrosController < ApplicationController
  def index
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  # GET /posts
  # GET /posts.json

  before_filter :require_login, :only => :secret
  def index
    @posts = Post.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @posts }
    end
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @post = Post.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @post }
    end
  end

  # GET /posts/new
  # GET /posts/new.json
  def new
    @post = Post.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @post }
    end
  end

  # GET /posts/1/edit
  def edit
    @post = Post.find(params[:id])
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(params[:post])

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Su post fue creado con exito!.' }
        format.json { render json: @post, status: :created, location: @post }
      else
        format.html { render action: "nuevo" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /posts/1
  # PUT /posts/1.json
  def update
    @post = Post.find(params[:id])

    respond_to do |format|
      if @post.update_attributes(params[:post])
        format.html { redirect_to @post, notice: 'Su post fue actualizado con exito!.' }
        format.json { head :no_content }
      else
        format.html { render action: "editar" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/sesion_controller.rb
class SesionController < ApplicationController
 before_filter :require_login, :only => :secret
  def iniciarsesion
  end

  def post
  end

  def registrarse
  end
  
  def destroy
  logout
  redirect_to root_url, :notice => "Logged out!"
end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
 before_filter :require_login, :only => :secret

def create
 usuario = login(params[:email], params[:password], params[:remember_me])
  if usuario
    redirect_back_or_to posts_path , :notice => "Logged in!"
  else
    flash.now.alert = "Email or password was invalid"
    render :new
  end
end

def destroy
  logout
  redirect_to root_url, :notice => "Logged out!"
end

end

app/controllers/usuarios_controller.rb
class UsuariosController < ApplicationController
  # GET /usuarios
  # GET /usuarios.json
  def index
    @usuario = Usuario.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @usuarios }
    end
  end

  # GET /usuarios/1
  # GET /usuarios/1.json
  def show
    @usuario = Usuario.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @usuario }
    end
  end

  # GET /usuarios/new
  # GET /usuarios/new.json
  def new
    @usuario = Usuario.new

   #   respond_to do |format|
    #   format.html # new.html.erb
    #   format.json { render json: @usuario }
    end
 

  # GET /usuarios/1/edit
  def edit
    @usuario = Usuario.find(params[:id])
  end

  # POST /usuarios
  # POST /usuarios.json
  def create
    @usuario = Usuario.new(params[:usuario])

if @usuario.save
    redirect_to root_url, :notice => "Signed up!"
  else
    render :new
  end
   #  respond_to do |format|
    #   if @usuario.save
    #     format.html { redirect_to @usuario, notice: 'Usuario was successfully created.' }
    #     format.json { render json: @usuario, status: :created, location: @usuario }
    #   else
    #     format.html { render action: "new" }
    #     format.json { render json: @usuario.errors, status: :unprocessable_entity }
    #   end
    #   end
  end

  # PUT /usuarios/1
  # PUT /usuarios/1.json
  def update
    @usuario = Usuario.find(params[:id])

    respond_to do |format|
      if @usuario.update_attributes(params[:usuario])
        format.html { redirect_to @usuario, notice: 'Usuario was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @usuario.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /usuarios/1
  # DELETE /usuarios/1.json
  def destroy
    @usuario = Usuario.find(params[:id])
    @usuario.destroy

    respond_to do |format|
      format.html { redirect_to usuarios_url }
      format.json { head :no_content }
    end
  end
 end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/AsideIzquierdo_helper.rb
module AsideIzquierdoHelper
end

app/helpers/Aside_Izquierdo_helper.rb
module AsideIzquierdoHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comentarios_helper.rb
module ComentariosHelper
end

app/helpers/contacto_helper.rb
module ContactoHelper
end

app/helpers/contactos_helper.rb
module ContactosHelper
end

app/helpers/nosotros_helper.rb
module NosotrosHelper
end

app/helpers/password_resets_helper.rb
module PasswordResetsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sesion_helper.rb
module SesionHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/usuarios_helper.rb
module UsuariosHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/contacto/index.html.erb
<h1>Contactos</h1>
<h3><p>Esparce tus ideas...</p></h3>
<br><br>
<div class='container'>
<form class="form-inline" role="form">
  <div class="form-group">
    <div class="input-group">
      <div class="input-group-addon">O </div>
      <input class="form-control" type="email" placeholder="usuario">
    </div>
  </div>
  <br>
  <br>
  <div class="form-group">
    <div class="input-group">
      <div class="input-group-addon">@</div>
      <input class="form-control" type="email" placeholder="Enter email">
    </div>
  </div>
  <br>
  <br>
 <textarea class="form-control" rows="3"  placeholder="Comentario"></textarea>
 <br>
 <br>
 <button type="submit" class="btn btn-primary">Submit</button>
</form>
</div>

app/views/posts/_form.html.erb
<%= form_for(@post ,html: {multipart: true}) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :titulo %><br>
    <%= f.text_field :titulo %>
  </div>
  
  <div class="field">
    <%= f.label "Imagen" %><br>
    <%= f.file_field :photo %>
  </div>
  
  <div class="actions">
    <%= f.submit "Subir" %>
  </div>
<% end %>

app/views/posts/_menu.html.erb
<div class="container">
</br>
	<div class="row">
		<div class="col-xs-12 col-md-2">
	
			<ul class="nav nav-pills nav-stacked">

				<li>
					<div class="media">
						<a class="pull-left" href="#"> <img class="img-rounded" src="/photo_store/artista.jpg" alt="foto de perfil" width="80" height="80"> </a>
						<div class="media-body">
							<div class="media-heading">
								<a href="#">Mi perfil</a>
							</div>
							<a href="#"><span class="glyphicon glyphicon-pencil"> </span>Editar</a>
						</div>
					</div>
				</li>

				<li class="active" >
					<a href="#" ><span class="glyphicon glyphicon-bullhorn"> </span> Notificaciones <span class="badge pull-right" >42</span></a>
				</li>
				<li>
					<a href="#"><span class="glyphicon glyphicon-folder-open"> </span> Portafolio</a>
				</li>
				<li>
					<a href="favoritos/index"><span class="glyphicon glyphicon-star"> </span> Favoritos</a>
				</li>
				<li>
					<a href="#"><span class="glyphicon glyphicon-eye-open"> </span> Populares</a>
				</li>

				<li class="dropdown">
					<a class="dropdown-toggle" data-toggle="dropdown" href="#"> <span class="glyphicon glyphicon-th-large"> </span> Categorías<span class="caret"></span> </a>
					<ul class="dropdown-menu" role="menu">

						<li>
							<a href="#">Ilustraciones</a>
						</li>
						<li>
							<a href="#">Dibujo artístico</a>
						</li>
						<li>
							<a href="#">Fotografía</a>
						</li>
						<li>
							<a href="#">Comics</a>
						</li>
					</ul>
				</li>

			</ul>

		</div>
	</div>
	

</div>

app/views/posts/edit.html.erb
 
  <div class="container">
    <div class="row" draggable="true">
<h1>Edición de post</h1>

<%= render 'form' %>

<%= link_to 'Mostrar', @post %> |
<%= link_to 'Atras', posts_path %>
</div>
</div>

app/views/posts/index.html.erb
</br>

<div class="row">

	<div class="col-xs-12 col-md-2">

		<%= render "menu" %>

	</div>
	<div class="col-xs-12 col-sm-12 col-md-9">

		<h1>Listado de posts</h1>

		<ul class='thumbnail' id='posts'  >
			<div class="row" draggable="true" >
				
				<div class="row gallery-row"><!-- Begin Gallery Row --> 
	      
			        <!-- Gallery Items
			        ================================================== --> 
			        <div class="span12 gallery">

			            <ul id="filterOptions" class="gallery-cats clearfix">
			                <li class="active"><a href="#" class="all">Todos</a></li> 
			                <li><a href="#" class="illustration">Ilustraciones</a></li>
			                <li><a href="#" class="design">Dibujo Artístico</a></li>
			                <li><a href="#" class="video">Fotografía</a></li>
			                <li><a href="#" class="web">Comics</a></li>
			            </ul>

						<% @posts.each do |post| %>
						<div id='post'>
							<div class="col-xs-12 col-sm-4" >
								<div class='thumbnail'>

									<% if post.has_photo? %>
									<a href="#"><%=image_tag post.photo_path %></a>
									<% end %>
									
									<!--	<%= link_to post.titulo , post %>  -->
									<button class="btn btn-link" data-toggle="modal" data-target="#myModal">
										<h4><span class="label label-primary"><%= post.titulo %></span> </h4>
									</button>
									<div class='caption'>

										<!-- Button trigger modal -->

										<!-- Modal -->
										<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
											<div class="modal-dialog">
												<div class="modal-content">
													<div class="modal-header">
														<button type="button" class="close" data-dismiss="modal">
															<span aria-hidden="true">&times;</span><span class="sr-only">Cerrar</span>
														</button>
														<h4 class="modal-title" id="myModalLabel"><%= post.titulo %></h4>
													</div>
													<div class="modal-body">
														<div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
														  <!-- Indicators -->
															<ol class="carousel-indicators">
																<li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
																<li data-target="#carousel-example-generic" data-slide-to="1"></li>
																<li data-target="#carousel-example-generic" data-slide-to="2"></li>
															</ol>

															<!-- Wrapper for slides -->
															<div class="carousel-inner">
																<div class="item active">
																 	<a><%=image_tag post.photo_path %></a>
																</div>
																<div class="item">
																  	<a><%=image_tag post.photo_path %></a>
																</div>
																...
															</div>

														  	<!-- Controls -->
														  	<a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
														    	<span class="glyphicon glyphicon-chevron-left"></span>
														  	</a>
														  	<a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
														    	<span class="glyphicon glyphicon-chevron-right"></span>
														  	</a>
														</div>
													</div>
													<div class="modal-footer">
														<button type="button" class="btn btn-default btn-md">
															<span class="glyphicon glyphicon-heart-empty"></span> Me gusta
														</button>
														<button type="button" class="btn btn-default btn-md">
															<span class="glyphicon glyphicon-comment"></span> Comentar
														</button>
													</div>
												</div>
											</div>
										</div>

										<button type="button" class="btn btn-default btn-md">
											<span class="glyphicon glyphicon-heart-empty"></span> Me gusta
										</button>
										<button type="button" class="btn btn-default btn-md">
											<span class="glyphicon glyphicon-comment"></span> Comentarios
										</button>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
				<% end %>
				</br>
			</div>
		</ul>
		<a class="btn btn-default" href="/posts/new" role="button"><span class="glyphicon glyphicon-upload" > </span> Nuevo post</a>
	</div>
</div>

<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
<!-- Include all compiled plugins (below), or include individual files as needed -->
<script src="js/bootstrap.min.js"></script>

app/views/posts/inicio.html.erb
<div class="intro-header">

    <div class="container">

      <div class="row">
        <div class="col-lg-12">
        
          <div class="intro-message" id="headerTitle">
            
            <h1>Smiles 4 Us</h1>
            <h3>Comparte tus trabajos con colegas.. :)</h3><i class="icon-search icon-large icon-white"></i>
            <hr class="intro-divider">
            <ul class="list-inline intro-social-buttons" >


              <li >
                <a  class="btn btn-primary btn-lg" href="usuarios/new" class="btn btn-default btn-lg">
                  
                  <span  >Únete </span>
                </a>
              </li>
              <li>
              	<a  class="btn btn-default btn-lg" href="sessions/new"  id="boton-sesion">
                 
                 
                  <span >Inicia Sesión</span>
                </a>
                
              </li>
            </ul>
          </div>
        </div>
      </div>

    </div>
  

  </div>
 

  <footer>
    <div class="container">
      <div class="row">
        <div class="col-lg-12">
          <ul class="list-inline">
            <li>
              <a href="index.html">Inicio</a>
            </li>
            <li class="footer-menu-divider"></li>
            <li>
              <a href="#about">Nosotros</a>
            </li>
            <li class="footer-menu-divider"></li>

            <li>
              <a href="#contact">Contactos</a>
            </li>
          </ul>
          <p class="copyright text-muted small">Copyright © Smiles4Us</p>
        </div>
      </div>
    </div>
  </footer>

  

app/views/posts/new.html.erb
  <div class="container">
    <div class="row" draggable="true">
  <h1>Nuevo post</h1>
  
<%= render 'form' %>
<%= link_to 'Atras', posts_path %>
</div>
</div>

app/views/posts/show.html.erb
<div class="container">
	<div class="row" draggable="true">
</br>
</br>
		<p id="notice">
			<%= notice %>
		</p>

		<p>
			<b>Titulo:</b>

			<%= @post.titulo %>
		</p>

		<p>
			<% if @post.has_photo? %>
		<p>
			<%= image_tag @post.photo_path %>
		</p>
		<% else %>
		<b>Tu foto no se cargo :(</b>

		<% end %>

		</p>

		<p>
			<button type="button" class="btn btn-default btn-lg">
				<span class="glyphicon glyphicon-heart-empty"></span> Me gusta
			</button>
			&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;77 Me gusta  |  15 comentarios
		</p>
		<p></p>
		<p>
			<textarea rows="3" cols="55">
Ingresa tu comentario...
</textarea>
</p>		<%= link_to 'Editar', edit_post_path(@post) %> |
		<%= link_to 'Atras', posts_path %>
		<br/>
		<br/>
		<br/>
		<br/>
		<br/>
		<br />
		<br/>
		<br/>
		<br/>
		<br/>
		<br/>
		<br/>
		<br/>
		<br/>
		<br/>
		<br/>
		<br/>
		<br/>

	</div>
</div>

app/views/usuarios/_form.html.erb
<%= form_for(@usuario) do |f|  %>
<% if @usuario.errors.any? %>
<div id="error_explanation">
	<h2><%= pluralize(@usuario.errors.count, "error") %> ..verifica que tus datos sean correctos :</h2>

	<ul>
		<% @usuario.errors.full_messages.each do |msg| %>
		<li>
			<%= msg %>
		</li>
		<% end %>
	</ul>
</div>
<% end %>
<div class="row">
  	<div class="col-md-4"></div>
  	<div class="col-md-4">

	  	<form class="form-horizontal" accept-charset="UTF-8" role="form" action="/usuarios/create" class="new_usuario" id="new_usuario" method="post">

		  	<div class="form-group">
				<div class="col-sm-10">
					<div class="field">
						<%= f.text_field :username, class: 'form-control',:placeholder => "Nombre de usuario" %>
					</div>
				</div>
			</div>

			<div class="form-group">
				<div class="col-sm-10">
					<div class="field">
						<%= f.text_field :email, class: 'form-control',:placeholder => "Correo electronico" %>
					</div>
				</div>
			</div>

			<div class="form-group">
				<div class="col-sm-10">
					<div class="field">
						<%= f.password_field :password, class: 'form-control',:placeholder => "Contraseña" %>
					</div>
				</div>
			</div>

			<div class="form-group">
				<div class="col-sm-10">
					<div class="field">
						<%= f.password_field :password_confirmation, class: 'form-control',:placeholder => "Confirmar contraseña"%>
					</div>
				</div>
			</div>
				
			<div class="form-group">
				<div class="col-sm-offset-2 col-sm-10">
					</br>
					<div class="actions" >
						<%= f.submit "Regístrate", class: "btn btn-primary btn-lg" %>
					</div>
				</div>
			</div>
		</form>
	</div>
  	<div class="col-md-4"></div>
</div>

</br>
</br>
<br/>
</br></br>
<br/>
</br></br>

<% end %>

app/views/usuarios/edit.html.erb
<h1>Editando usuario</h1>

<%= render 'form' %>

<%= link_to 'Mostrar', @usuario %> |
<%= link_to 'Atrás', usuarios_path %>

app/views/usuarios/index.html.erb
<h1>Lista de usuarios</h1>

<table>
  <tr>
    <th>Nombre de Usuario</th>
    <th>Correo Electrónico</th>
    <th>Contraseña Encriptada</th>
    <th>Salt</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @usuarios.each do |usuario| %>
  <tr>
    <td><%= usuario.username %></td>
    <td><%= usuario.email %></td>
    <td><%= usuario.crypted_password %></td>
    <td><%= usuario.salt %></td>
    <td><%= link_to 'Mostrar', usuario %></td>
    <td><%= link_to 'Editar', edit_usuario_path(usuario) %></td>
    <td><%= link_to 'Destruir', usuario, confirm: 'Estas seguro?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'Nuevo Usuario', new_usuario_path %>

app/views/usuarios/new.html.erb
 <% content_for :header do %>
<div class="intro-header">
  <div class="container">
    <div class="row">
      <div class="col-lg-12">
        <div class="intro-message-session">
          <h1 class="text-center" id="headerTitle">Smiles 4 Us</h1>
<% end %>
<% content_for :footer do %>
        </div>
      </div>
    </div>
  </div>
</div>

<footer>
    <div class="container">
      <div class="row">
        <div class="col-lg-12">
          <ul class="list-inline">
            <li>
              <a href="index.html">Inicio</a>
            </li>
            <li class="footer-menu-divider">⋅</li>
            <li>
              <a href="#about">Nosotros</a>
            </li>
            <li class="footer-menu-divider">⋅</li>

            <li>
              <a href="#contact">Contactos</a>
            </li>
          </ul>
          <p class="copyright text-muted small">Copyright © Smiles4Us</p>
        </div>
      </div>
    </div>
  </footer>

 
<% end %>
<%= yield :header %>
<%= render 'form' %>
<%= yield :footer %>

<%= link_to 'Atrás', usuarios_path %>

app/views/usuarios/show.html.erb
</br>
</br>
<p id="notice"><%= notice %></p>

<p>
  <b>Nombre de usuario:</b>
  <%= @usuario.username %>
</p>

<p>
  <b>Correo electrónico:</b>
  <%= @usuario.email %>
</p>




<%= link_to 'Editar', edit_usuario_path(@usuario) %> |
<%= link_to 'Atràs', usuarios_path %>