config/routes.rb
Smiles4usv3::Application.routes.draw do

  resources :contactos

  get "subscripciones/index"

  get "nosotros/index"

  get "contacto/index"

  resources :comentarios

  get "favoritos/index"

  get "password_resets/create"

  get "password_resets/edit"

  get "password_resets/update"

  get "usuarios/new"

  get "sessions/new"

  resources :usuarios

  get "sesion/iniciarsesion"

  get "sesion/post"

  get "sesion/registrarse"

  get "welcome/index"
  
  
  
  get "logout" => "sessions#destroy", :as => "logout"
get "login" => "sessions#new", :as => "login"
get "signup" => "usuarios#new", :as => "signup"
resources :usuarios
resources :sessions
  

  resources :posts
  resources :sesion
  
  resources :password_resets
 

 root :to => 'posts#inicio'

end

app/models/comentario.rb
class Comentario < ActiveRecord::Base
 
  attr_accessible :texto, :usuario_id
  
   validates_presence_of :texto
   validates :texto, :texto => { :maximun => 140 }
end

app/models/post.rb
class Post < ActiveRecord::Base
  attr_accessible :photo,:titulo, :usuario_id
 belongs_to :usuario
  FOTOS = File.join Rails.root, 'public','photo_store'
  after_save :guardar_foto
  def photo=(file_data)
    unless file_data.blank?
      @file_data = file_data
      self.extension = file_data.original_filename.split('.').last.downcase
    end
  end

  def photo_filename
    File.join FOTOS, "#{id}.#{extension}"
  end

  def photo_path
    "/photo_store/#{id}.#{extension}"
  end

  def has_photo?
    File.exists? photo_filename

  end

  private

  def guardar_foto
    if @file_data
      FileUtils.mkdir_p FOTOS
      File.open(photo_filename, 'wb') do |f|
        f.write(@file_data.read)
      end
      @file_data = nil
    end
  end
end

app/models/usuario.rb
class Usuario < ActiveRecord::Base
 has_many :posts
 authenticates_with_sorcery!
  attr_accessible :crypted_password, :email, :salt, :username, :password_confirmation , :password
  validates_confirmation_of :password, message: "Ambos campos deben coincidir", if: :password
  validates_presence_of :password, :on => :create
  validates_presence_of :email
  validates_uniqueness_of :email
end

app/controllers/contacto_controller.rb
class ContactoController < ApplicationController
  def index
  end  
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  # GET /posts
  # GET /posts.json

  before_filter :require_login, :only => :secret
  def index
    @posts = Post.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @posts }
    end
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @post = Post.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @post }
    end
  end

  # GET /posts/new
  # GET /posts/new.json
  def new
    @post = Post.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @post }
    end
  end

  # GET /posts/1/edit
  def edit
    @post = Post.find(params[:id])
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(params[:post])

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Su post fue creado con exito!.' }
        format.json { render json: @post, status: :created, location: @post }
      else
        format.html { render action: "nuevo" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /posts/1
  # PUT /posts/1.json
  def update
    @post = Post.find(params[:id])

    respond_to do |format|
      if @post.update_attributes(params[:post])
        format.html { redirect_to @post, notice: 'Su post fue actualizado con exito!.' }
        format.json { head :no_content }
      else
        format.html { render action: "editar" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/sesion_controller.rb
class SesionController < ApplicationController
 before_filter :require_login, :only => :secret
  def iniciarsesion
  end

  def post
  end

  def registrarse
  end
  
  def destroy
  logout
  redirect_to root_url, :notice => "Logged out!"
end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/AsideIzquierdo_helper.rb
module AsideIzquierdoHelper
end

app/helpers/Aside_Izquierdo_helper.rb
module AsideIzquierdoHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comentarios_helper.rb
module ComentariosHelper
end

app/helpers/contacto_helper.rb
module ContactoHelper
end

app/helpers/contactos_helper.rb
module ContactosHelper
end

app/helpers/nosotros_helper.rb
module NosotrosHelper
end

app/helpers/password_resets_helper.rb
module PasswordResetsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sesion_helper.rb
module SesionHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/usuarios_helper.rb
module UsuariosHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<html>

	<head>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<meta name="description" content="Red social de portafolio">
		<meta name="author" content="Gabriel Rodriguez, Justhine Tumbaco, Ronny Valdivieso, Rafael Mayor, Jose Cordova">
	<!--	<link href="http://fonts.googleapis.com/css?family=Lato:100,300,400,700,900,100italic,300italic,400italic,700italic,900italic" rel="stylesheet"> -->
		<title>Smiles4us</title>
		<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
		<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
		<%= javascript_include_tag 'cufon-replace', 'data-turbolinks-track' => true %>
	<link href='http://fonts.googleapis.com/css?family=Oswald' rel='stylesheet' type='text/css'>
<link rel="stylesheet" href="bootstrap.css">
<link rel="stylesheet" href="bootstrap-responsive.css">
<link rel="stylesheet" href="prettyPhoto.css" />
<link rel="stylesheet" href="custom-styles.css">
<link rel="shortcut icon" href="favicon.ico">
<link rel="apple-touch-icon" href="apple-touch-icon.png">
<link rel="apple-touch-icon" sizes="72x72" href="apple-touch-icon-72x72.png">
<link rel="apple-touch-icon" sizes="114x114" href="apple-touch-icon-114x114.png">
<script src="http://code.jquery.com/jquery-1.8.3.min.js"></script>
<script src="bootstrap.js"></script>
<script src="jquery.prettyPhoto.js"></script>
<script src="jquery.custom.js"></script>
<script type="text/javascript">
    $(document).ready(function () {

    $("#btn-blog-next").click(function () {
      $('#blogCarousel').carousel('next')
    });
     $("#btn-blog-prev").click(function () {
      $('#blogCarousel').carousel('prev')
    });

     $("#btn-client-next").click(function () {
      $('#clientCarousel').carousel('next')
    });
     $("#btn-client-prev").click(function () {
      $('#clientCarousel').carousel('prev')
    });
    
    $('#myCarousel').carousel({
        interval: 4000
    });
    $('#myCarousel').carousel('cycle');
});

</script>
	
	</head>

	<body>
		
		<% content_for :navbar do %>
		
		<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
			<div class="container">
				<div class="navbar-header">
					<button class="navbar-toggle collapsed" data-target=".navbar-ex1-collapse" data-toggle="collapse" type="button">
						<span class="sr-only">Desplegar Navegacion</span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
					</button>
					<a class="navbar-brand" href="/posts">Smiles 4 Us <span class="glyphicon glyphicon-heart-empty"></span></a>

				</div>

				<!-- Collect the nav links, forms, and other content for toggling -->

				<div class="collapse navbar-collapse navbar-right navbar-ex1-collapse">

					<ul class="nav navbar-nav">
						<li>
							<% if current_user %>
						
							<li>
								<a><a class="pull-left" href="#"> <img class="img-circle" src="/photo_store/artista.jpg" alt="foto de perfil" width="25" height="25">   <%= current_user.username %></a></a>
							</li>
							
							<li>
								<a><%= link_to 'Editar mi cuenta', edit_usuario_path(current_user) %></a>
							</li>
							
							<li>
								<a> <%= link_to "Cerrar sesión", logout_path %> </a>
							</li>
							<% else %>
	                         <li>
								<a> <%= link_to "Explorar", posts_path %> </a>
							</li>
							<li>
								<a> <%= link_to "Únete", signup_path %> </a>
							</li>
							<!-- <li><span class="glyphicon glyphicon-heart-empty"></span></li> -->
							<li>
								<a> <%= link_to "Iniciar sesión", login_path %> </a>
							</li>

							<li>
								<form class="navbar-form navbar-left" role="search">
							        <div class="form-group">
							          <input type="text" class="form-control" placeholder="Ingresa tu búsqueda">
							        </div>
	        						<button type="submit" class="btn btn-default">Buscar</button>
	      						</form>
							</li>
							<% end %>
						</li>
					</ul>
				</div>
				<!-- /.navbar-collapse -->
			</div>
			<!-- /.container -->
		</nav>
		<br>
		<br>
		<% end %>

		<%= yield :navbar %>

		<%= yield %>

	</body>
</html>